### ISSUE TITLE
LLDB header files may have moved

### ISSUE THREAD

**Issue by dijkstracula** [endoli/lldb-sys.rs#15]
Caveat: I'm used to using `ptrace` and `libdwarf` directly instead of using LLVM infrastructure, and am also a Rust newbie, so I could well be off the mark here.

Hi,

I've checked out and built LLVM, and set `LLVM_ROOT` and `LLVM_BUILD_ROOT`, essentially using the following abbreviated steps:

```
$ pwd
/Users/ntaylor/code
$ git clone https://github.com/llvm/llvm-project.git
$ cd llvm_project; mkdir build; cd build
$ cmake -DLLDB_INCLUDE_TESTS=OFF -DLLVM_ENABLE_PROJECTS="clang;lldb" -G "Unix Makefiles" ../llvm`
...
$ export LLVM_ROOT=~/code/llvm-project
$ export LLVM_BUILD_ROOT=~/code/llvm-project/build
```

However, I get the following `lldb-sys` build error:

```
$ cargo build
   Compiling lldb-sys v0.0.27
   Compiling libc v0.2.107
The following warnings were emitted during compilation:

warning: In file included from src/lldb/UnityBuild.cpp:1:
warning: src/lldb/Bindings/SBAddressBinding.cpp:10:10: fatal error: 'lldb/API/LLDB.h' file not found
warning: #include "lldb/API/LLDB.h"
warning:          ^~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `lldb-sys v0.0.27`
```

A quick glance at where that header lives:

```
$ pwd
/Users/ntaylor/code/llvm-project
$ find . -name 'LLDB.h'
./lldb/include/lldb/API/LLDB.h
$
```

Not a problem to fix simply by copying that directory tree into my `build/ directory...

```
$ cp -r lldb/include/lldb build/include
$ find . -name 'LLDB.h'
./lldb/include/lldb/API/LLDB.h
./build/include/lldb/API/LLDB.h
$ cargo build
   Compiling lldb-sys v0.0.27
   Compiling lldb v0.0.10
   Compiling ivydb v0.1.0 (/Users/ntaylor/code/ivydb)
    Finished dev [unoptimized + debuginfo] target(s) in 1.43s
```

I wonder whether `$LLVM_ROOT/build/include` should be passed to rustc to search for headers?  

Thanks!

**Comment by waywardmonkeys** [comment]
Sorry for the delay in answering. I haven't done a build in a while, but you shouldn't have needed to copy the headers, I thought. I'm unclear whether or not something has changed in LLVM since I last built. (It has been a while since I moved to doing more on Linux than macOS.)

I'm also thinking about copying a version of the headers into `lldb-sys` so that it can link against a shared library but not need to find the headers. What do you think about that possibly happening?

**Comment by dijkstracula** [comment]
Good question, all I know is all that I've reported - do you know whether checking out that all-in-one repo is the canonical way of building Clang these days?  I seem to remember needing to check out LLVM separately to Clang in the distant past.

> I'm also thinking about copying a version of the headers into lldb-sys so that it can link against a shared library
> but not need to find the headers. What do you think about that possibly happening?

I suppose this would solve the issue modulo bitrot - seems like one more annoying piece of state you'd have to track as LLVM evolves ;)

**Comment by waywardmonkeys** [comment]
I have made this much easier by depending on the home brew packaging for builds on macOS. No longer need to build LLDB yourself! Just either set `LLVM_CONFIG` in the env or make sure it is on the path. This is also done now in CI to make sure things keep working.
