### ISSUE TITLE
Why does this package needs llvm source?

### ISSUE THREAD

**Issue by SlNPacifist** [endoli/lldb-sys.rs#2]
Hi!
I'm a newbee to working on library-linked crates and my task is to make this package work in linux. Working on Ubuntu 16.04 64-bit I managed to make it work (still need some experience to send a good PR), however, main question is: why is this crate needs llvm source?
I mean there are bindings generated from LLDB API header files. These header files were taken from some version of LLDB. Is not it better to put all needed files (those are from `lldb/include`, `llvm/include` and `build/include`). There is only one file (`Compiler.h` from `llvm` includes) that requires `build/include` file and this include can be ignored.
What I did for the first time:
- checked out `llvm`,
- checked out `lldb` into `llvm/tools`
- checked out `clang` in `llvm/tools`
- run `cmake` to generate `/build` files
- built this crate using `println!("cargo:rustc-link-lib=lldb-3.8");` instead of frameworks and setting needed env variables.

What I did for the second time:
- copied llvm/includes into a separate directory within a crate source
- copied lldb/includes into a separate directory within a crate source
- commented out unnecessary include in `Compiler.h`
- built this crate without using any references to external files.

In both cases I got working library that was used to run and close /bin/ls using LLDB (I had lldb 3.8 installed from http://apt.llvm.org/). 

Are there reasons for `llvm` header files to be excluded from this package?

**Comment by waywardmonkeys** [comment]
No, there's no reason, I just hadn't done it yet. Are you up to submitting a pull request that I can take a look at?

**Comment by SlNPacifist** [comment]
Closing due to PR #4
